import { BingoBall } from "@interfaces/index";

const gameBingoBalls: BingoBall[] = [
  { name: "B", number: 1, selected: false, enabled: false },
  { name: "B", number: 2, selected: false, enabled: false },
  { name: "B", number: 3, selected: false, enabled: false },
  { name: "B", number: 4, selected: false, enabled: false },
  { name: "B", number: 5, selected: false, enabled: false },
  { name: "B", number: 6, selected: false, enabled: false },
  { name: "B", number: 7, selected: false, enabled: false },
  { name: "B", number: 8, selected: false, enabled: false },
  { name: "B", number: 9, selected: false, enabled: false },
  { name: "B", number: 10, selected: false, enabled: false },
  { name: "B", number: 11, selected: false, enabled: false },
  { name: "B", number: 12, selected: false, enabled: false },
  { name: "B", number: 13, selected: false, enabled: false },
  { name: "B", number: 14, selected: false, enabled: false },
  { name: "B", number: 15, selected: false, enabled: false },

  { name: "I", number: 16, selected: false, enabled: false },
  { name: "I", number: 17, selected: false, enabled: false },
  { name: "I", number: 18, selected: false, enabled: false },
  { name: "I", number: 19, selected: false, enabled: false },
  { name: "I", number: 20, selected: false, enabled: false },
  { name: "I", number: 21, selected: false, enabled: false },
  { name: "I", number: 22, selected: false, enabled: false },
  { name: "I", number: 23, selected: false, enabled: false },
  { name: "I", number: 24, selected: false, enabled: false },
  { name: "I", number: 25, selected: false, enabled: false },
  { name: "I", number: 26, selected: false, enabled: false },
  { name: "I", number: 27, selected: false, enabled: false },
  { name: "I", number: 28, selected: false, enabled: false },
  { name: "I", number: 29, selected: false, enabled: false },
  { name: "I", number: 30, selected: false, enabled: false },

  { name: "N", number: 31, selected: false, enabled: false },
  { name: "N", number: 32, selected: false, enabled: false },
  { name: "N", number: 33, selected: false, enabled: false },
  { name: "N", number: 34, selected: false, enabled: false },
  { name: "N", number: 35, selected: false, enabled: false },
  { name: "N", number: 36, selected: false, enabled: false },
  { name: "N", number: 37, selected: false, enabled: false },
  { name: "N", number: 38, selected: false, enabled: false },
  { name: "N", number: 39, selected: false, enabled: false },
  { name: "N", number: 40, selected: false, enabled: false },
  { name: "N", number: 41, selected: false, enabled: false },
  { name: "N", number: 42, selected: false, enabled: false },
  { name: "N", number: 43, selected: false, enabled: false },
  { name: "N", number: 44, selected: false, enabled: false },
  { name: "N", number: 45, selected: false, enabled: false },

  { name: "G", number: 46, selected: false, enabled: false },
  { name: "G", number: 47, selected: false, enabled: false },
  { name: "G", number: 48, selected: false, enabled: false },
  { name: "G", number: 49, selected: false, enabled: false },
  { name: "G", number: 50, selected: false, enabled: false },
  { name: "G", number: 51, selected: false, enabled: false },
  { name: "G", number: 52, selected: false, enabled: false },
  { name: "G", number: 53, selected: false, enabled: false },
  { name: "G", number: 54, selected: false, enabled: false },
  { name: "G", number: 55, selected: false, enabled: false },
  { name: "G", number: 56, selected: false, enabled: false },
  { name: "G", number: 57, selected: false, enabled: false },
  { name: "G", number: 58, selected: false, enabled: false },
  { name: "G", number: 59, selected: false, enabled: false },
  { name: "G", number: 60, selected: false, enabled: false },

  { name: "O", number: 61, selected: false, enabled: false },
  { name: "O", number: 62, selected: false, enabled: false },
  { name: "O", number: 63, selected: false, enabled: false },
  { name: "O", number: 64, selected: false, enabled: false },
  { name: "O", number: 65, selected: false, enabled: false },
  { name: "O", number: 66, selected: false, enabled: false },
  { name: "O", number: 67, selected: false, enabled: false },
  { name: "O", number: 68, selected: false, enabled: false },
  { name: "O", number: 69, selected: false, enabled: false },
  { name: "O", number: 70, selected: false, enabled: false },
  { name: "O", number: 71, selected: false, enabled: false },
  { name: "O", number: 72, selected: false, enabled: false },
  { name: "O", number: 73, selected: false, enabled: false },
  { name: "O", number: 74, selected: false, enabled: false },
  { name: "O", number: 75, selected: false, enabled: false },
];

export default gameBingoBalls;
